### ISSUE TITLE
Where is Phone_ringing, ongoing_call feature?

### ISSUE THREAD

**Issue by hanumanjiblog** [Paradoxu/Caller#12]
Where is Phone_ringing, ongoing_call feature?

**Comment by Paradoxu** [comment]
As of now the app will only be notified once the call is ended, with either `incoming` or `outgoing` alongside with the phone number, I may add the requested functionality in the future.

**Comment by Paradoxu** [comment]
Duplicate of [11](https://github.com/Paradoxu/Caller/issues/11)
