### ISSUE TITLE
Asking permission wheneever app is intiated 

### ISSUE THREAD

**Issue by oddmentiusmaximus** [Paradoxu/Caller#3]
Even when the initialize method is not insert as soon as the app opens the permission popups come and if declined and then manually called later for request permission nothing happens

**Comment by Paradoxu** [comment]
Sadly this is a default behavior for android, once the user has denied the permission, android won't show the alert reasking for permission anymore, with the version `2.0.1+` a screen showing the Application settings will be shown when reasking for permissions once they have been denied;
