### ISSUE TITLE
Unable to save caller details

### ISSUE THREAD

**Issue by subhashish-bacancy** [Paradoxu/Caller#4]
I am trying to save the caller details which I am getting in the callback but it's always null outside the callback handler.

```
  static Future<void> callerCallbackHandler(
    CallerEvent event,
    String number,
    int? duration,
  ) async {
    /* Performing tasks according to the triggered events */
    print('This is the event :- $event $number');
    phnNum = number;
    if (phnNum != null) {
      print('This is not null');
    }
    switch (event) {
      case CallerEvent.callEnded:
        break;
      case CallerEvent.onMissedCall:
        break;
      case CallerEvent.onIncomingCallAnswered:
        break;
      case CallerEvent.onIncomingCallReceived:
        break;
    }
  }
```

phnNum is always null but inside the callback it has the value.

**Comment by Paradoxu** [comment]
> I am trying to save the caller details which I am getting in the callback but it's always null outside the callback handler.
> 
> ```
>   static Future<void> callerCallbackHandler(
>     CallerEvent event,
>     String number,
>     int? duration,
>   ) async {
>     /* Performing tasks according to the triggered events */
>     print('This is the event :- $event $number');
>     phnNum = number;
>     if (phnNum != null) {
>       print('This is not null');
>     }
>     switch (event) {
>       case CallerEvent.callEnded:
>         break;
>       case CallerEvent.onMissedCall:
>         break;
>       case CallerEvent.onIncomingCallAnswered:
>         break;
>       case CallerEvent.onIncomingCallReceived:
>         break;
>     }
>   }
> ```
> 
> phnNum is always null but inside the callback it has the value.

Hi, hou are you using phnNum? Could you provide a more detailed sample code, since the problem doesn't seem to be with the library, there must be something you missed.

**Comment by subhashish-bacancy** [comment]
```
import 'dart:async';
import 'package:caller/caller.dart';
import 'package:permission_handler/permission_handler.dart';

class CallService {
  /* Sigleton call service class for managing call events */
  static final CallService shared = CallService.internal();
  factory CallService() => shared;
  CallService.internal();
  /* call details here:- */
  String? number;
  CallerEvent? event;
  int? duration;

/* Handler for handling call events should be a static or top level function */
  static Future<void> callerCallbackHandler(
    CallerEvent event,
    String number,
    int? duration,
  ) async {
    /* Performing tasks according to the triggered events */
    switch (event) {
      case CallerEvent.callEnded:
        break;
      case CallerEvent.onMissedCall:
        break;
      case CallerEvent.onIncomingCallAnswered:
        break;
      case CallerEvent.onIncomingCallReceived:
        CallService.shared.saveData(event, number, duration);
        break;
    }
  }

  void saveData(
    CallerEvent event,
    String number,
    int? duration,
  ) {
    this.event = event;
    this.number = number;
    this.duration = duration;
  }

  Future<void> initialize() async {
    /* Check if the user has granted permissions */
    final permission = await Permission.phone.request();
    if (permission.isGranted) {
      Caller.initialize(callerCallbackHandler);
    } else {
      /* Show alert and ask for permission */
    }
  }
}
```



This is my call service class I just want to save the event number and duration but I always get null accessing it outside the static callback method and I also tried with top level function.

**Comment by Paradoxu** [comment]
So, you are trying to share this `CallService` between your application and the background `caller` ? If so, I'm sorry to say, but you can't share data that way, background calls run in a separate isolated and do not share any data with your main application, in your case, your `CallService` is a singleton, that is created twice, one for you main application isolate, and one for the background call. 

An easy approach to use, is to register the call events in a database that can be then shared and used with your main application.
