### ISSUE TITLE
caller: ^2.0.1 plugin showing errer

### ISSUE THREAD

**Issue by bharatallam** [Paradoxu/Caller#7]
C:\flutter_windows_2.10.5-stable\flutter.pub-cache\hosted\pub.dartlang.org\caller-2.0.1\android\src\main\kotlin\me\leoletto\caller\CallerPlugin.kt: (28, 1): Class 'CallerPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener e: C:\flutter_windows_2.10.5-stable\flutter.pub-cache\hosted\pub.dartlang.org\caller-2.0.1\android\src\main\kotlin\me\leoletto\caller\CallerPlugin.kt: (164, 3): 'onRequestPermissionsResult' overrides nothing

**Comment by hanumanjiblog** [comment]
Caller Package Not Working, Please Fix It
@Paradoxu

**Comment by Paradoxu** [comment]
Fixed with version 2.0.2! I apologize for the waiting time, I've been having some issues lately.
